window.VisualPrototypeScreens = [
  { group: "Overview", slug: "site-map", title: "全体サイトマップ", reference: "00-1. 全体サイトマップ画像.png", kind: "overview" },
  { group: "Overview", slug: "db-map", title: "DB接続・データ関係図", reference: "00-2. DB接続・データ関係図画像.png", kind: "overview" },
  { group: "Customer", slug: "top", title: "トップページ", reference: "01. index.html トップページ.png", kind: "customer-top" },
  { group: "Customer", slug: "customer-login", title: "会員ログイン", reference: "02. customer login.html 会員ログインページ.png", kind: "customer-login" },
  { group: "Customer", slug: "customer-index", title: "会員トップ", reference: "03. customer index.html 会員トップページ.png", kind: "customer-dashboard" },
  { group: "Customer", slug: "questionnaire", title: "初回アンケート", reference: "04. customer questionnaire.html 初回アンケートページ.png", kind: "questionnaire" },
  { group: "Customer", slug: "questionnaire-step2", title: "分岐後アンケート", reference: "05. customer questionnaire_step2.html 分岐後アンケートページ.png", kind: "questionnaire" },
  { group: "Customer", slug: "fragrance-graph", title: "通常結果ページ", reference: "06. customer fragrance-graph.html 通常結果ページ.png", kind: "result" },
  { group: "Customer", slug: "fragrance-graph-compare", title: "会員比較モード", reference: "07. 親：customer fragrance-graph.html 会員比較モード.png", kind: "result" },
  { group: "Customer", slug: "fragrance-graph-modal", title: "比較拡大モーダル", reference: "08. 子：customer fragrance-graph.html 比較拡大モーダル.png", kind: "modal" },
  { group: "Customer", slug: "reservation", title: "来店予約", reference: "09. customer reservation.html 来店予約ページ.png", kind: "reservation" },
  { group: "Customer", slug: "reservation-complete", title: "予約完了", reference: "10. customer reservation-complete.html 予約完了ページ.png", kind: "complete" },
  { group: "Customer", slug: "product-reservation", title: "QR商品作成依頼", reference: "11. customer product-reservation.html QR商品作成依頼ページ.png", kind: "product-request" },
  { group: "Customer", slug: "shipping-info", title: "発送先入力", reference: "12. customer shipping-info.html 発送先入力ページ.png", kind: "shipping" },
  { group: "Auth", slug: "admin-login", title: "共通ログイン", reference: "13. admin-login.html 共通ログインページ.png", kind: "admin-login" },
  { group: "Staff", slug: "staff-dashboard", title: "スタッフダッシュボード", reference: "14. staff staff-dashboard.html スタッフダッシュボード.png", kind: "staff-dashboard" },
  { group: "Staff", slug: "staff-reservations", title: "スタッフ予約一覧", reference: "15. staff staff-reservations.html スタッフ予約一覧ページ.png", kind: "staff-table" },
  { group: "Staff", slug: "staff-slots", title: "予約枠作成", reference: "16. staff staff-slots.html 予約枠作成ページ.png", kind: "staff-slots" },
  { group: "Staff", slug: "staff-customer-detail", title: "スタッフ専用詳細", reference: "17. 親：staff staff-customer-detail.html スタッフ専用詳細ページ.png", kind: "staff-detail" },
  { group: "Staff", slug: "staff-balance-modal", title: "香りのバランス調整モーダル", reference: "18. 子：staff-customer-detail 香りのバランス調整モーダル.png", kind: "staff-modal" },
  { group: "Staff", slug: "staff-product-modal", title: "商品名入力モーダル", reference: "19. 子：staff-customer-detail 商品名入力モーダル.png", kind: "staff-modal" },
  { group: "Staff", slug: "staff-consent-modal", title: "同意確認モーダル", reference: "20. 子：staff-customer-detail 同意確認モーダル.png", kind: "staff-modal" },
  { group: "Admin", slug: "admin-dashboard", title: "管理者ダッシュボード", reference: "21. admin admin-dashboard.html 管理者ダッシュボード.png", kind: "admin-dashboard" },
  { group: "Admin", slug: "admin-settings", title: "基本設定・店舗情報", reference: "22. admin admin-settings.html 基本設定・店舗情報ページ.png", kind: "admin-settings" },
  { group: "Admin", slug: "admin-scoring", title: "配点ロジック調整", reference: "23. admin admin-scoring.html 配点ロジック調整ページ.png", kind: "admin-scoring" },
  { group: "Admin", slug: "admin-materials", title: "原料ポイント編集", reference: "24. admin admin-materials.html 原料ポイント編集ページ.png", kind: "admin-materials" },
  { group: "Admin", slug: "admin-qr-settings", title: "QR商品設定", reference: "25. admin admin-qr-settings.html QR商品設定ページ.png", kind: "admin-qr" },
  { group: "Admin", slug: "admin-qr-modal", title: "QR関連通知詳細モーダル", reference: "26. admin admin-dashboard.html QR関連通知詳細モーダル.png", kind: "admin-modal" }
];
